import React from "react";
import { Head, Html, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="bg-gray-50 max-w-3xl mx-auto">
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
